version: '3'
services:
#  mysql:
#    image: mysql:5.7.26
#    volumes:
#      - ./src/db/mysql-data:/var/lib/mysql
#    environment:
#      - TZ=Asia/Tokyo
#      - MYSQL_ROOT_PASSWORD=root
#    ports:
#      - 3306:3306

  api:
    build: .
    command: gunicorn --bind :8080 --workers 1 --threads 8 main:app
    volumes:
      - ./src:/app
    ports:
      - 8080:8080
    environment:
      - TZ=Asia/Tokyo
    tty: true
#    depends_on:
#      - mysql

