version: '3'
services:
#  mysql:
#    image: mysql:5.7.26
#    volumes:
#      - ./src/db/mysql-data:/var/lib/mysql
#    environment:
#      - TZ=Asia/Tokyo
#      - MYSQL_ROOT_PASSWORD=root
#    ports:
#      - 3306:3306

  api:
    build: .
    container_name: api
    command: >
      bash -c "gunicorn --bind :8080 --workers 1 --threads 8 main:app
      && wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy
      && chmod +x cloud_sql_proxy
      && ./cloud_sql_proxy -instances=flaskrun:asia-northeast1:myinstance=tcp:3306 -credential_file=flaskrun-develop.json"
    volumes:
      - ./src:/app
    ports:
      - 8080:8080
    environment:
      - TZ=Asia/Tokyo
    tty: true
    stdin_open: true
#    depends_on:
#      - mysql

