version: '3'
services:
#  mysql:
#    image: mysql:5.7.26
#    volumes:
#      - ./mysql-data:/var/lib/mysql
#    environment:
#      - MYSQL_ROOT_PASSWORD=password
#      - MYSQL_USER=root
#      - MYSQL_PASSWORD=root
#      - MYSQL_DATABASE=guestbook
#    ports:
#      - 3306:3306

  api:
    build: .
    container_name: api
    command: >
      bash -c "apt-get update
      && apt-get install -y wget
      && wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy
      && chmod +x cloud_sql_proxy
      && gunicorn --bind :8080 --workers 1 --threads 8 main:app --reload -D
      && ./cloud_sql_proxy -instances=flaskrun:asia-northeast1:myinstance=tcp:3306 -credential_file=flaskrun-develop.json"
    volumes:
      - ./src:/app
    ports:
      - 8080:8080
    environment:
      - TZ=Asia/Tokyo
      - ENV=dev
      - CLOUD_SQL_CONNECTION_NAME=flaskrun:asia-northeast1:myinstance
      - DB_USER=root
      - DB_PASS=12345678
      - DB_NAME=guestbook
    tty: true
    stdin_open: true
#    depends_on:
#      - mysql

