apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: gcr.io/flaskrun/helloworld
        env:
        - name: TARGET
          value: "Python Sample v1"
